# Generated by autorevision - do not hand-hack!

VCS_TYPE="git"
VCS_BASENAME="autorevision"
VCS_UUID="da2830f81fec4c6ebce8ebf23f35b0e6b066c149"
VCS_NUM="241"
VCS_DATE="2014-06-10T19:09:31-0400"
VCS_BRANCH="master"
VCS_TAG="v/1.9"
VCS_TICK="6"
VCS_EXTRA=""

VCS_FULL_HASH="0ec5c47a272f22c1a7ce97ba07e8678625cf157a"
VCS_SHORT_HASH="0ec5c47"

VCS_WC_MODIFIED="0"

# end
