/* Generated by autorevision - do not hand-hack! */

#ifndef AUTOREVISION_AUTOREVISION_H
#define AUTOREVISION_AUTOREVISION_H

namespace autorevision
{
	const std::string VCS_TYPE		= "git";
	const std::string VCS_BASENAME	= "autorevision";
	const std::string VCS_UUID		= "da2830f81fec4c6ebce8ebf23f35b0e6b066c149";
	const int VCS_NUM				= 292;
	const std::string VCS_DATE		= "2015-07-31T21:15:47-0400";
	const std::string VCS_BRANCH	= "master";
	const std::string VCS_TAG		= "v/1.12";
	const int VCS_TICK				= 9;
	const std::string VCS_EXTRA		= "";

	const std::string VCS_FULL_HASH		= "56d31c116f8239ae38f2c251946cd5811c47afe1";
	const std::string VCS_SHORT_HASH	= "56d31c1";

	const int VCS_WC_MODIFIED			= 0;
}

#endif

/* end */
