<?php
# Generated by autorevision - do not hand-hack!

$GLOBAL["VCS_TYPE"] = "git";
$GLOBAL["VCS_BASENAME"] = "autorevision";
$GLOBAL["VCS_UUID"] = "da2830f81fec4c6ebce8ebf23f35b0e6b066c149";
$GLOBAL["VCS_NUM"] = 221;
$GLOBAL["VCS_DATE"] = "2014-01-02T09:49:29-0500";
$GLOBAL["VCS_BRANCH"] = "master";
$GLOBAL["VCS_TAG"] = "v/1.8";
$GLOBAL["VCS_TICK"] = 9;
$GLOBAL["VCS_EXTRA"] = "";

$GLOBAL["VCS_FULL_HASH"] = "f8246efccfd575be2388255ef1d180b2ebbe8293";
$GLOBAL["VCS_SHORT_HASH"] = "f8246ef";

$GLOBAL["VCS_WC_MODIFIED"] = false;

# end
?>
