-- Generated by autorevision - do not hand-hack!

VCS_TYPE = "git"
VCS_BASENAME = "autorevision"
VCS_UUID = "da2830f81fec4c6ebce8ebf23f35b0e6b066c149"
VCS_NUM = 336
VCS_DATE = "2016-02-25T03:38:41Z"
VCS_BRANCH = "master"
VCS_TAG = "v/1.14"
VCS_TICK = 11
VCS_EXTRA = ""

VCS_ACTION_STAMP = "2016-02-25T03:38:41Z!dak180@users.sourceforge.net"
VCS_FULL_HASH = "a37506ae793f6fbde92936b76aa99341ca4c5199"
VCS_SHORT_HASH = "a37506a"

VCS_WC_MODIFIED = false

-- end
