/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"autorevision"
#define VCS_UUID		"da2830f81fec4c6ebce8ebf23f35b0e6b066c149"
#define VCS_NUM			424
#define VCS_DATE		"2017-09-26T03:57:45Z"
#define VCS_BRANCH		"topic/gpg"
#define VCS_TAG			"v/1.20"
#define VCS_TAG_OPENPGP	"A16E4FE1BFE882DE9D6E28AD0044B6E72C414317"
#define VCS_TICK		16
#define VCS_EXTRA		""

#define VCS_ACTION_STAMP	"2017-09-26T03:57:45Z!dak180@users.sourceforge.net"
#define VCS_FULL_HASH		"c009f3afa47dc7cc2bcf789f37cdea8c91a32f5e"
#define VCS_COMMIT_OPENPGP	"A16E4FE1BFE882DE9D6E28AD0044B6E72C414317"
#define VCS_SHORT_HASH		"c009f3a"

#define VCS_WC_MODIFIED		0

#endif

/* end */
