/* Generated by autorevision - do not hand-hack! */

const char *VCS_TYPE         = "git";
const char *VCS_BASENAME     = "autorevision";
const char *VCS_UUID         = "da2830f81fec4c6ebce8ebf23f35b0e6b066c149";
const int VCS_NUM            = 339;
const char *VCS_DATE         = "2016-03-16T19:00:26Z";
const char *VCS_BRANCH       = "master";
const char *VCS_TAG          = "v/1.14";
const int VCS_TICK           = 14;
const char *VCS_EXTRA        = "";

const char *VCS_ACTION_STAMP = "2016-03-16T19:00:26Z!dak180@users.sourceforge.net";
const char *VCS_FULL_HASH    = "7159703f9c5d2bc7bd7236b4560c2474f019b835";
const char *VCS_SHORT_HASH   = "7159703";

const int VCS_WC_MODIFIED     = 1;

/* end */
