/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"autorevision"
#define VCS_UUID		"da2830f81fec4c6ebce8ebf23f35b0e6b066c149"
#define VCS_NUM			208
#define VCS_DATE		"2013-12-26T12:23:44-0500"
#define VCS_BRANCH		"master"
#define VCS_TAG			"v/1.7"
#define VCS_TICK		6
#define VCS_EXTRA			""

#define VCS_FULL_HASH		"5dcfe1bf64940ff93aa3229d477fafa7c50a0032"
#define VCS_SHORT_HASH		"5dcfe1b"

#define VCS_WC_MODIFIED		1

#endif

/* end */
