/* Generated by autorevision - do not hand-hack! */

public class autorevision {
    public static final String VCS_TYPE = "git";
    public static final String VCS_BASENAME = "autorevision";
    public static final String VCS_UUID = "da2830f81fec4c6ebce8ebf23f35b0e6b066c149";
    public static final long VCS_NUM = 221;
    public static final String VCS_DATE = "2014-01-02T09:49:29-0500";
    public static final String VCS_BRANCH = "master";
    public static final String VCS_TAG = "v/1.8";
    public static final long VCS_TICK = 9;
    public static final String VCS_EXTRA = "";

    public static final String VCS_FULL_HASH = "f8246efccfd575be2388255ef1d180b2ebbe8293";
    public static final String VCS_SHORT_HASH = "f8246ef";

    public static final boolean VCS_WC_MODIFIED = false;
}
