# Generated by autorevision - do not hand-hack!

VCS_TYPE = "git"
VCS_BASENAME = "autorevision"
VCS_UUID = "da2830f81fec4c6ebce8ebf23f35b0e6b066c149"
VCS_NUM = 208
VCS_DATE = "2013-12-26T12:23:44-0500"
VCS_BRANCH = "master"
VCS_TAG = "v/1.7"
VCS_TICK = 6
VCS_EXTRA = ""

VCS_FULL_HASH = "5dcfe1bf64940ff93aa3229d477fafa7c50a0032"
VCS_SHORT_HASH = "5dcfe1b"

VCS_WC_MODIFIED = True

# end
