# Generated by autorevision - do not hand-hack!

set(VCS_TYPE git)
set(VCS_BASENAME autorevision)
set(VCS_UUID da2830f81fec4c6ebce8ebf23f35b0e6b066c149)
set(VCS_NUM 378)
set(VCS_DATE 2016-11-06T06:33:23Z)
set(VCS_BRANCH master)
set(VCS_TAG v/1.15)
set(VCS_TICK 27)
set(VCS_EXTRA )

set(VCS_ACTION_STAMP 2016-11-06T06:33:23Z!luqiuwen@nelmail.iie.ac.cn)
set(VCS_FULL_HASH da460a16856496b888c24774941cb6521fa80c57)
set(VCS_SHORT_HASH da460a1)

set(VCS_WC_MODIFIED 1)

# end
