/* Generated by autorevision - do not hand-hack! */

#ifndef ASTROGRAPH_AUTOREVISION_H
#define ASTROGRAPH_AUTOREVISION_H

namespace astrograph
{
    const std::string VCS_TYPE     = "git";
    const std::string VCS_BASENAME = "ASTROGRAPH";
    const std::string VCS_UUID     = "71b897a43ec3c90edec23568d823548bc7522ca7";
    const int VCS_NUM              = 734;
    const std::string VCS_DATE     = "2014-10-02T17:48:38-1000";
    const std::string VCS_BRANCH   = "release/CRAVEN-IOC";
    const std::string VCS_TAG      = "";
    const int VCS_TICK             = 734;
    const std::string VCS_EXTRA    = "";

    const std::string VCS_FULL_HASH  = "411edd1dc0e4dcbbecfa3c417d87f8ab40e2424f";
    const std::string VCS_SHORT_HASH = "411edd1";

    const int VCS_WC_MODIFIED = 0;
}

#endif

/* end */
