-- Generated by autorevision - do not hand-hack!
DROP TABLE IF EXISTS vcs;
CREATE TABLE vcs (
   type           VARCHAR(8),
   basename       VARCHAR(45),
   uuid           VARCHAR(45),
   num            INTEGER UNSIGNED,
   date           VARCHAR(45),
   branch         VARCHAR(45),
   full_hash      VARCHAR(45),
   short_hash     VARCHAR(10)
);

INSERT INTO vcs (type,basename,uuid,num,date,branch,tag,
                 tick,extra,full_hash,short_hash,wc_modified)
       VALUES ('git','third-party','c082332ca242d6652d37dd7e95dfda05dd15f995',3,'2014-08-21T16:30:24-1000',
               'master', '2fef860c288a6e25cc38a0c4c9f788768206b708','2fef860';
-- end
