/* Generated by autorevision - do not hand-hack! */

const char *VCS_TYPE      	 	 = "git";
const char *VCS_BASENAME    	 = "autorevision";
const char *VCS_UUID			 = "da2830f81fec4c6ebce8ebf23f35b0e6b066c149";
const int VCS_NUM				 = 424;
const char *VCS_DATE        	 = "2017-09-26T03:57:45Z";
const char *VCS_BRANCH      	 = "topic/gpg";
const char *VCS_TAG         	 = "v/1.20";
const char *VCS_TAG_OPENPGP		 = "A16E4FE1BFE882DE9D6E28AD0044B6E72C414317";
const int VCS_TICK				 = 16;
const char *VCS_EXTRA		 = "";

const char *VCS_ACTION_STAMP	 = "2017-09-26T03:57:45Z!dak180@users.sourceforge.net";
const char *VCS_FULL_HASH   	 = "c009f3afa47dc7cc2bcf789f37cdea8c91a32f5e";
const char *VCS_COMMIT_OPENPGP	 = "A16E4FE1BFE882DE9D6E28AD0044B6E72C414317";
const char *VCS_SHORT_HASH		 = "c009f3a";

const int VCS_WC_MODIFIED		 = 0;

/* end */
