-- Generated by autorevision - do not hand-hack!
DROP TABLE IF EXISTS vcs;
CREATE TABLE vcs (
	type				VARCHAR(8),
	basename			VARCHAR(45),
	uuid				VARCHAR(45),
	num					INTEGER UNSIGNED,
	date				VARCHAR(45),
	branch				VARCHAR(45),
	full_hash			VARCHAR(45),
	short_hash			VARCHAR(10)
);

INSERT INTO vcs (type,basename,uuid,num,date,branch,tag,
				tick,extra,full_hash,short_hash,wc_modified)
		VALUES ('git','autorevision','da2830f81fec4c6ebce8ebf23f35b0e6b066c149',289,'2015-07-30T20:19:11-0400',
			'master', '18ff79342483d3b3f839b6c5968194a23f5263b1','18ff793';
-- end
