#!/usr/bin/env python
# encoding: utf-8

import waflib

APPNAME = 'projectname'
VERSION = '1.0' # This will be overwritten later.


def configure(bld):
    bld.load('Utils')
    # This makes sure that autorevision exists before we call it.
    bld.find_program('autorevision', var='AUTOREVISION')
    print(bld.path.abspath())


def options(bld):
    pass


def dist(bld):
    # This is where the cache file is made and VERSION is rewritten.
    global VERSION
    VERSION = bld.cmd_and_log("autorevision -s VCS_TAG -o autorevision.cache", quiet=0, cwd=bld.path.abspath()).strip()


def build(bld):

    # Here we let waf know about the autorevision.cache file.
    dist(bld) # just to update
    autorevision_cache_node = bld.path.find_or_declare('autorevision.cache')

    # This is where the autorevision.json file is made.
    bld(
        rule='${AUTOREVISION} -f -t json -o ${SRC[0].abspath()} > ${TGT}',
        source=autorevision_cache_node,
        target='autorevision.json')

    # This is where the autorevision.h file is made.
    bld(
        rule='${AUTOREVISION} -f -t h -o ${SRC[0].abspath()} > ${TGT}',
        source=autorevision_cache_node,
        target='autorevision.h')
