#!/usr/bin/env python
# encoding: utf-8

APPNAME = 'something'
VERSION = '1.0' # This will be overwritten later.


def options(opt):
	opt.load('compiler_cxx')


def configure(conf):
	conf.load('compiler_cxx')
	ctx.find_program('autorevision', var='AUTOREVISION')

def dist(ctx):
	global VERSION
	VERSION = ctx.cmd_and_log("autorevision -s VCS_TAG -o autorevision.cache", quiet=0).strip()


def build(bld):
	autorevision_cache_node = bld.path.find_or_declare('autorevision.cache')

	bld(
		rule='${AUTOREVISION} -f -t json -o ${SRC} > ${TGT}',
		source=autorevision_cache_node,
		target='autorevision.json')

	bld(
		rule='${AUTOREVISION} -f -t h -o ${SRC} > ${TGT}',
		source=autorevision_cache_node,
		target='autorevision.h')

	bld.program(
		source='example.cpp',
		target='app',
		cxxflags='-std=c++11')
